config/routes.rb
Rails.application.routes.draw do

  # FB log in, controller part added
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  resources :bookmates, only: [:show, :index] do
    resources :selling_books, only: [:show, :new, :create]
    resource :loved_bookstore, only: [:create, :destroy]
  end
  resources :orders, only: [:show, :new, :create, :update]

  #post 'orders/:id/delivered', to: 'orders#delivered'
  post 'orders/:id/reviewed', to: 'orders#reviewed'
  #post 'bookmates/:id/loved_bookstores', to: 'bookmates#bookmarked'
  # post 'selling_books/:id/liked', to: 'selling_books#liked'

  resources :books, only: [:show] do
    resource :loved_book, only: [:create, :destroy]
  end

  resources :selling_books, only: [:edit, :update]

  get 'search', to: 'bookmates#search'

  mount Attachinary::Engine => "/attachinary"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit, :update] do
    resources :conversations, only: [:index, :create] do
      resources :messages, only: :create
    end
  end

  post 'orders/:id/delivered', to: 'orders#delivered'


  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

  # post 'books/:id/create', to: 'loved_books#create'
  # post 'bookmates/:id/loved_bookstores', to: 'loved_bookstores#bookmate_liked'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :loved_books, dependent: :destroy
  has_many :books, through: :loved_books
  has_many :bookmates, dependent: :destroy
  has_many :bookmate_book_categories, through: :bookmates
  has_many :selling_books, through: :bookmate_book_categories
  has_many :orders
  has_many :messages, dependent: :nullify
  has_many :loved_bookstores, dependent: :destroy

  has_attachment :photo
  # after_create :send_welcome_email

  validates :email, presence: :true, uniqueness: :true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # FB log in
  devise :omniauthable,  omniauth_providers: [:facebook]

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  # Facebook part
  def self.picture_url(url)
    url.insert(-1, "?&width=1000&height=1000&redirect=false")
    rep = JSON.parse(open(url).read)
    rep["data"]["url"]
  end

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = picture_url(auth.info.image)
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h
    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end
    return user
  end

  def save_loved_books(isbn)
    loved_book_isbns = books.pluck(:isbn)
    books_to_love = Book.where(isbn: isbn).where.not(isbn: loved_book_isbns)

    books_to_love.each do |book|
      loved_books.create(book: book)
    end
  end

  def conversations
    Conversation.includes(:messages)
                .where("user1_id = :id OR user2_id = :id", id: id)
                .order("messages.created_at DESC")
  end

  def other_user(conversation)
    conversation.users.include?(self) ? conversation.other_user(self) : nil
  end

  def unread_messages
    scope = Conversation.where(user1_id: self.id).or(Conversation.where(user2_id: self.id)).map { |conversation| conversation.messages }.flatten
    scope.select { |m| m.read? }
  end

  def unread_messages_count
    unread_messages.count
  end

  def unread_messages?
    unread_messages_count > 0
  end

  private

  # mail on user creation
  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: :show

  def show
    @paid_orders = Order.all.where(order_status: "paid").where(user: current_user).order("created_at DESC")
    @undelivered_orders = Order.all.where(order_status: "paid").where(delivery_status: "en cours").where(user: current_user)
    @delivered_orders = Order.all.where(order_status: "paid").where(delivery_status: "effectuée").where(user: current_user).order("created_at DESC")
    @commented_orders = Order.all.where.not(review: nil).where(user: current_user).order("updated_at DESC")
    @uncommented_orders = Order.all.where(review: nil, order_status: "paid").where(user: current_user)
    @user = User.find(params[:id])
    @loved_books = LovedBook.all.where(user: current_user)
    @loved_bookstores = LovedBookstore.all.where(user: current_user)
    authorize @user
  end

  def edit
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = current_user
    current_user.update(user_params)
    current_user.save
    authorize @user
    redirect_to user_path(current_user)
  end


  private

  def user_params
    params.require(:user).permit(:name, :description, :password, :password_confirmation, :photo)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_bookmate.html.erb
<h1>Mes favoris</h1>
<div class="fav-bookmates">
  <% @loved_bookstores.each do |loved_bookstore| %>
    <div class="user-avatar-bookmate text-center">
      <div class = "card-user text-center">
          <%= cl_image_tag loved_bookstore.bookmate.user.photo.path  %>
      </div>
        <h2>
          <%= loved_bookstore.bookmate.user.first_name %>
        </h2>
    </div>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <%= f.input :photo, as: :attachinary %>
  <%= f.button :submit %>
<% end %>

app/views/users/_order.html.erb
  <div class="card-grey-dashboard">
    <div class="order-bookmate text-center">
      <%= cl_image_tag order.bookmate.user.photo.path, :width=>80, :height=>80, :gravity=>"auto", :crop=>"fill", class:"bookmate-avatar"  %>

      <h2><%= order.bookmate.user.first_name  %></h2>
    </div>

    <div class="order-description">

      <h2>Détail de la commande </h2>
      <% counter= 0 %>
      <% order.selling_books.each do |selling_book| %>
        <% counter += 1 %>
        <div class="order-book-list">
          <p><%= selling_book.book.title %> - <%= selling_book.book.author %></p>

          <% if current_user.loved_books.where(book: selling_book.book).exists? %>
            <%= link_to book_loved_book_path(selling_book.book), method: :delete, class: "blue", id: "like#{counter}" do %>
              <i class="fa fa-heart" aria-hidden="true"></i>
            <% end %>
          <% else %>
            <%= link_to book_loved_book_path(selling_book.book), method: :post, class: "blue", id: "like#{counter}" do %>
              <i class="fa fa-heart-o" ></i>
            <% end %>
          <% end %>
        </div>

      <% end %>
      <h2 class="order-delivery"><span class="text-bold">Mode de livraison :</span>  <%= order.delivery_type %></h2>
    </div>

    <div class="order-details">
        <h2 class="order-date"><%= order.created_at.strftime('%d.%m.%y') %></h2>

        <% if order.review.present? %>
          <!-- Comment done -->
          <div class="review-right" id="thank-review#{order.id}">
            <p class="green bold">Commentaire ajouté</p>
          </div>
        <% else %>
          <!-- Button trigger modal -->
          <button type="button" id="btn-comment<%= order.id %>" class="btn-bookshare-red review-right" data-toggle="modal" data-target="#myModal<%= order.id %>">
            Faire un commentaire
          </button>
        <% end %>
        <!-- Modal -->
        <div class="modal fade" id="myModal<%= order.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
    <!--           <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div> -->
              <div class="modal-body">


                <div id= "form-review#{order.id}" >
                  <%= simple_form_for @order, :url => url_for(:action => 'reviewed', :controller => 'orders', :id => order.id), :method => 'post' do |f| %>
                    <%= hidden_field_tag :order_id, order.id %>
                    <%= f.input :review, :label => "Faites un retour sur votre expérience" %>
                    <div class="rating">

                      <input type="radio" value="5" name="order[rating]" id="order_rating_5">
                      <label class="collection_radio_buttons" for="order_rating_5"></label>

                      <input type="radio" value="4" name="order[rating]" id="order_rating_4">
                      <label class="collection_radio_buttons" for="order_rating_4"></label>

                      <input type="radio" value="3" name="order[rating]" id="order_rating_3">
                      <label class="collection_radio_buttons" for="order_rating_3"></label>

                      <input type="radio" value="2" name="order[rating]" id="order_rating_2">
                      <label class="collection_radio_buttons" for="order_rating_2"></label>
                      <input type="radio" value="1" name="order[rating]" id="order_rating_1">
                      <label class="collection_radio_buttons" for="order_rating_1"></label>

                    </div>

                    <div class="modal-footer">
                    <%= f.submit "Envoyer le commentaire",class: " btn-bookshare-red",id: "save-review#{order.id}"%>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>
  </div>



<% content_for :after_js do %>
  <%= javascript_tag do %>
    $(document).ready(function() {

      $('#myModal<%= order.id %>').on('shown.bs.modal', function () {
        $('#thank-review<%= order.id %>').hide();
        $('#myInput').focus();

      })

    });
  <% end %>
<% end %>

app/views/users/_profile.html.erb
<h1>Mon profil</h1>
<% if current_user.photo? %>
  <%= cl_image_tag current_user.photo.path, alt: "profile picture", class: "avatar-large" %>
<% elsif current_user.facebook_picture_url%>
  <%= image_tag current_user.facebook_picture_url, alt: "profile picture", class: "avatar-large" %>
<%else%>
  <%= image_tag "http://placehold.it/100x100", alt: "profile picture", class: "avatar-large" %>
<% end %>

<% if policy(@user).update? %>
  <%= link_to "Editer mon profil", edit_user_path(current_user), class: "btn-bookshare-red" %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
    <h1>Edit your profile</h1>
    <div class="row">
      <div class="col-xs-12 col-sm-4 col-sm-offset-4">
        <div class="form-container">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>

app/views/users/show.html.erb
  <!-- Cette row contient le Dashboard -->
    <!-- Cette colonne contient la barre latérale -->
    <div class="sidebar">
      <h3>MON COMPTE</h3>
      <div class="tabs">
        <a class="tab active" data-target="#orders">
          <h2>Mes commandes</h2>
        </a>
        <a class="tab" data-target="#bookmates">
          <h2>Mes favoris</h2>
        </a>
        <a class="tab" data-target="#loved_books">
          <h2>Mes livres préférés</h2>
        </a>
        <a class="tab" data-target="#comments">
          <h2>Mes commentaires</h2>
        </a>
        <a class="tab" data-target="#profile">
          <h2>Mon profil</h2>
        </a>
      </div>
    </div>
    <!-- Cette colonne contient le contenu des tabs -->
    <div class = "col-xs-offset-2 col-xs-10">
    <!--       Contenu des commandes -->
          <div class="tab-content" id="orders">

            <h1>Mes commandes</h1>
            <% @paid_orders.each do |paid_order| %>
              <div>
              <%= render "order", order: paid_order %>
              </div>
            <% end %>

          </div>
<!--       Contenu du profil -->
      <div class="tab-content hidden" id="profile">
        <%= render "profile"%>
      </div>
<!--       Contenu des commentaires -->
      <div class="tab-content hidden" id="comments">
        <h1>Les commentaires à laisser</h1>
        <% @uncommented_orders.each do |uncommented_order| %>
          <div>
            <%= render "comment", order: uncommented_order %>
          </div>
          <h2><%= uncommented_order.bookmate.user.first_name  %></h2>

          <button type="button" id="btn-comment<%= uncommented_order.id %>" class="btn btn-primary" data-toggle="modal" data-target="#myModalUncommentedOrder<%= uncommented_order.id %>">
            Faire un commentaire
          </button>

          <!-- Modal -->
          <div class="modal fade" id="myModalUncommentedOrder<%= uncommented_order.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">

                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>

                <div class="modal-body">

                  <div id="thank-review#{uncommented_order.id}">
                    <p>Vos commentaires ont bien été pris en compte</p>
                  </div>

                  <div id= "form-review#{uncommented_order.id}" >
                    <%= simple_form_for @order, :url => url_for(:action => 'reviewed', :controller => 'orders', :id => uncommented_order.id), :method => 'post' do |f| %>
                      <%= hidden_field_tag :order_id, :label => "Faites un retour sur votre expérience"%>
                       <div class="rating">

                          <input type="radio" value="5" name="order[rating]" id="order_rating_5bis">
                          <label class="collection_radio_buttons" for="order_rating_5bis"></label>

                          <input type="radio" value="4" name="order[rating]" id="order_rating_4bis">
                          <label class="collection_radio_buttons" for="order_rating_4bis"></label>

                          <input type="radio" value="3" name="order[rating]" id="order_rating_3bis">
                          <label class="collection_radio_buttons" for="order_rating_3bis"></label>

                          <input type="radio" value="2" name="order[rating]" id="order_rating_2bis">
                          <label class="collection_radio_buttons" for="order_rating_2bis"></label>
                          <input type="radio" value="1" name="order[rating]" id="order_rating_1bis">
                          <label class="collection_radio_buttons" for="order_rating_1bis"></label>

                        </div>

                      <div class="modal-footer">
                        <%= f.button :submit, "Envoyer le commentaire",class: "btn btn-primary",id: "save-review#{uncommented_order.id}"%>
                      </div>

                    <% end %>
                  </div>

                </div>
              </div>
            </div>
          </div>

        <% end %>

        <h1>Les commentaires que vous avez laissé</h1>
        <% @commented_orders.each do |commented_order| %>
          <div>
            <%= render "comment", order: commented_order %>
            <%= commented_order.review %>
            <%= commented_order.rating  %>
          </div>
        <% end %>
      </div>
<!--       Contenu des livres préférés -->
      <div class="tab-content hidden" id="loved_books">
        <h1>Mes livres préférés</h1>
        <div class="card-grey">

          <div class="books">
            <% @loved_books.each do |loved_book| %>
              <div class="book">
                <%= cl_image_tag loved_book.book.photo.path %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
<!--       Contenu des bookmates -->
      <div class="tab-content hidden" id="bookmates">
        <%= render "bookmate"%>
      </div>


    </div>