config/routes.rb
Rails.application.routes.draw do

  # FB log in, controller part added
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  resources :bookmates, only: [:show, :index] do
    resources :selling_books, only: [:show, :new, :create]
    resource :loved_bookstore, only: [:create, :destroy]
  end
  resources :orders, only: [:show, :new, :create, :update]

  #post 'orders/:id/delivered', to: 'orders#delivered'
  post 'orders/:id/reviewed', to: 'orders#reviewed'
  #post 'bookmates/:id/loved_bookstores', to: 'bookmates#bookmarked'
  # post 'selling_books/:id/liked', to: 'selling_books#liked'

  resources :books, only: [:show] do
    resource :loved_book, only: [:create, :destroy]
  end

  resources :selling_books, only: [:edit, :update]

  get 'search', to: 'bookmates#search'

  mount Attachinary::Engine => "/attachinary"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit, :update] do
    resources :conversations, only: [:index, :create] do
      resources :messages, only: :create
    end
  end

  post 'orders/:id/delivered', to: 'orders#delivered'


  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

  # post 'books/:id/create', to: 'loved_books#create'
  # post 'bookmates/:id/loved_bookstores', to: 'loved_bookstores#bookmate_liked'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="icons-left">
    <div class="list-inline">
      <a href=""><i class="fa fa-youtube"></i></a>
      <a href=""><i class="fa fa-instagram"></i></a>
      <a href=""><i class="fa fa-facebook"></i></a>
      <a href=""><i class="fa fa-twitter"></i></a>
    </div>
  </div>
  <div class="text-right">
    <p>Proudly developed by Camille, Anne-Sophie & Quentin © BookShare 2017</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", class: "navbar-wagon-logo" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <div class="navbar-wagon-item">
        Vendez vos livres
      </div>

      <!-- Button (call-to-action) -->
      <% if current_page?(root_path) %>
      <% else %>
        <div class="navbar-wagon-item" id="btn-find-nav">
          <%= render 'shared/searchform' %>
        </div>
      <% end %>

      <!-- enveloppe -->
      <div class="navbar-enveloppe">
        <div class="badge-container">
          <% if user_signed_in? %>
            <%= link_to  user_conversations_path(current_user) do%>
              <% if @messages_count == 0 %>
                <i class="fa fa-envelope-o"></i>
              <% else %>
                <i class="fa fa-envelope-o"></i>
                <div class="badge badge-red"><%= @messages_count %></div>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
      <!-- basket -->

      <div class="navbar-cart">
        <div class="badge-container">
          <% if current_order && current_order.persisted? %>
            <%= link_to order_path(current_order) do %>
              <%= image_tag "shopping-cart-grey.png", class: "shopping-cart-logo" %>
              <div class="badge badge-red"><%= @basket_counter %></div>
            <% end %>
          <% else %>
            <%= image_tag "shopping-cart-grey.png", class: "shopping-cart-logo" %>
          <% end %>
        </div>
      </div>




      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.photo? %>
            <%= cl_image_tag current_user.photo.path, alt: "profile picture", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown"%>
          <% else %>
          <!-- Choose fb picture or uploaded picture -->
            <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
          <%# avatar_url = current_user.facebook_picture_url || current_user.photo.path || "http://placehold.it/30x30" %>
          <!-- cloudinary ? -->
            <%= image_tag avatar_url, alt: "profile picture", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown"%>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Dashboard") %>
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <div class="navbar-wagon-item navbar-wagon-item-box">
        Devenez Bookmate
      </div>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Se connecter"), new_user_session_path, class: "navbar-wagon-item" %>

    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_searchform.html.erb
  <%= form_tag(search_path, method: 'get', id: 'searchform_navbar') do %>
    <%= hidden_field_tag "isbn[]", nil, id: "isbn_1" %>
    <%= hidden_field_tag "isbn[]", nil, id: "isbn_2" %>
    <%= hidden_field_tag "isbn[]", nil, id: "isbn_3" %>

    <%= hidden_field_tag :latitude %>
    <%= hidden_field_tag :longitude %>
    <%= submit_tag 'Trouver un livre', class: 'navbar-wagon-item navbar-wagon-button', id: "submitsearch_navbar", disabled: "disabled"%>
  <% end %>