config/routes.rb
Rails.application.routes.draw do

  # FB log in, controller part added
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  resources :bookmates, only: [:show, :index] do
    resources :selling_books, only: [:show, :new, :create]
    resource :loved_bookstore, only: [:create, :destroy]
  end
  resources :orders, only: [:show, :new, :create, :update]

  #post 'orders/:id/delivered', to: 'orders#delivered'
  post 'orders/:id/reviewed', to: 'orders#reviewed'
  #post 'bookmates/:id/loved_bookstores', to: 'bookmates#bookmarked'
  # post 'selling_books/:id/liked', to: 'selling_books#liked'

  resources :books, only: [:show] do
    resource :loved_book, only: [:create, :destroy]
  end

  resources :selling_books, only: [:edit, :update]

  get 'search', to: 'bookmates#search'

  mount Attachinary::Engine => "/attachinary"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit, :update] do
    resources :conversations, only: [:index, :create] do
      resources :messages, only: :create
    end
  end

  post 'orders/:id/delivered', to: 'orders#delivered'


  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

  # post 'books/:id/create', to: 'loved_books#create'
  # post 'bookmates/:id/loved_bookstores', to: 'loved_bookstores#bookmate_liked'
end

app/models/bookmate.rb
class Bookmate < ApplicationRecord
  belongs_to :user
  has_many :bookmate_book_categories, dependent: :destroy
  has_many :selling_books,through: :bookmate_book_categories, dependent: :destroy
  has_many :books, through: :selling_books
  has_many :orders, dependent: :destroy
  has_many :loved_bookstores, dependent: :destroy


  validates :description, presence: :true
  validates :deliver_by_hand, inclusion: { in: [ true, false ] }
  validates :home_delivery, inclusion: { in: [ true, false ] }

  def review_count
    orders.where.not(review: nil).count
  end

  def average_rating
    return if review_count == 0

    return orders.where.not(rating: nil).average(:rating).round
  end
end

app/controllers/bookmates_controller.rb
class BookmatesController < ApplicationController
  skip_after_action :verify_policy_scoped, only: [:search, :index]
  before_action :set_bookmate, only: [:show]

  def show
    authorize @bookmate
    @count = 0
    @bookmate_book_categories = BookmateBookCategory.all

    if @bookmate.deliver_by_hand == true
      @count = @count + 1
    end

    if @bookmate.home_delivery == true
      @count = @count + 1
    end
  end

  def index
    @bookmates = Bookmate.all
  end

  def search
    @address = [params[:latitude],params[:longitude]].join(",")
    @isbn = params[:isbn]

    if user_signed_in?
      loved_book_isbns = current_user.books.pluck(:isbn)

      # Add selected books to user loved books
      if @isbn.present?
        current_user.save_loved_books(@isbn)
      end

      # Include loved books to bookmate search
      if !@isbn.nil?
        @isbn += loved_book_isbns
      end
    else
      session[:isbn_to_love] = @isbn
    end

    #recupere un array de ISBN > comparer les bookstore collections avec cet array
    @users_near_me = User.near(@address, 10)
    # @bookmates_near_me = @users_near_me.map { |user| user.bookmates }.flatten
    @bookmates_near_me = Bookmate.where(user_id: @users_near_me.map(&:id))

    @bookmates_matching = @bookmates_near_me.
      select("bookmates.*, COUNT(books.id) AS common_books").
      joins(:books).
      where(books: { isbn: @isbn }).
      group("bookmates.id").
      order("common_books DESC")


    # FIXME
    # @bookmates_selected.each do |bookmate|
    #   @common_books = Book.where(books: { isbn: @isbn }).size
    # end
    # duplicates = @bookmates_selected.detect { |element| @bookmates_selected.count(element) > 1 }
    # if duplicates != 0
    #   @bookmates_selected = duplicates.first
    # end

    # raise
    # @common_books = @bookmates_selected.map { |book| Book.where(books: { isbn: @isbn }) }
    # @common_books = Book.where(books: { isbn: @isbn })
    # @intersection = @isbn & @common_books
    # raise
    if @bookmates_matching.exists?
      @bookmates_selected = @bookmates_matching
    else
      @bookmates_selected = @bookmates_near_me
    end

    @hash = Gmaps4rails.build_markers(@bookmates_selected) do |bookmate, marker|
      marker.lat bookmate.user.latitude
      marker.lng bookmate.user.longitude
      marker.infowindow render_to_string(partial: 'infowindow', locals: { bookmate: bookmate })
    end
    #   @hash = Gmaps4rails.build_markers(@bookmates_selected) do |bookmate, marker|
    #     marker.lat bookmate.user.latitude
    #     marker.lng bookmate.user.longitude
    #     marker.infowindow render_to_string(partial: 'infowindow', locals: { bookmate: bookmate })
    #   end
    # end
  end




  private

  def set_bookmate
    @bookmate = Bookmate.find(params[:id])
  end


  private

  def loved_bookstore_params
    params.require(:loved_bookstore).permit(:user, :bookmate)

  end
end

#if intersection.empty?
#ordering search > people with matches come first, then closest to me

app/helpers/bookmates_helper.rb
module BookmatesHelper
end

app/views/bookmates/_infowindow.html.erb
<div class="infowindow">
  <% if bookmate.user.photo? %>
    <%= cl_image_tag bookmate.user.photo.path, class: "card-user avatar"%>
    <%= link_to "", bookmate_path(bookmate.user), class: "card-link"  %>
  <% else %>
    <%= image_tag "https://www.bunnyholder.com/30/30", class: "card-user avatar"%>
    <%= link_to "", bookmate_path(bookmate.user), class: "card-link"  %>
  <% end %>
  <h2><%= bookmate.user.first_name %></h2>
</div>

app/views/bookmates/index.html.erb
<div class="container-search">
<!-- Bloc map et cards -->
  <div class="row">
      <!-- Bloc cards -->

      <div class="col-xs-7" id="card-column">
        <% @bookmates.each do |bookmate|%>
          <!-- Carte utilisateur -->
          <div class="position-relative">

            <div class="card-grey-dashboard">

              <div class="order-bookmate text-center">
                  <% if bookmate.user.photo? %>
                    <%= cl_image_tag bookmate.user.photo.path,:width=>80, :height=>80, :gravity=>"auto", :crop=>"fill", class: "bookmate-avatar" %>
                  <% else %>
                    <%= image_tag 'avatar.png',:width=>80, :height=>80, :gravity=>"auto", :crop=>"fill" %>
                  <% end %>
              </div>

              <div class="user-details">
                <%= link_to bookmate_path(bookmate) do %>

                  <h2 class="dark-grey weighted"><%= bookmate.user.first_name %></h2>
                  <p>" <%= bookmate.description %> "</p>
                <% end %>

                <!-- <h2 style="padding-left: 30vh"> -->
                <div class="rating-search">
                  <p class="blue"> <i class="fa fa-commenting"></i> <%= bookmate.review_count%></p>
                  <% if bookmate.average_rating %>
                    <% bookmate.average_rating.times do %>
                      <i class="fa fa-star blue"></i>
                    <% end %>
                    <% (5 - bookmate.average_rating).times do %>
                      <i class="fa fa-star grey"></i>
                    <% end %>
                  <% end %>
                </div>
                <!-- </h2> -->
              </div>


              <div class="common-book-number" data-toggle="modal" data-target="#common-books-modal<%= bookmate.id %>">
                <% if bookmate.respond_to?(:common_books) %>
                    <%= pluralize bookmate.common_books, "livre" %> en commun
                <% else %>
                    Aucun livre en commun
                <% end %>

              </div>

              <div class="modal fade books-modal" id="common-books-modal<%= bookmate.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <% if bookmate.respond_to?(:common_books) %>
                         <h3>Vos livres en commun avec <%= bookmate.user.first_name %></h3>
                    <% else %>
                        <h3>Vous n'avez aucun livre en commun avec <%= bookmate.user.first_name %> </h3>
                    <% end %>

                    <div class="common-books">

                        <% current_user.loved_books.each do |loved_book| %>
                          <% bookmate.selling_books.each do |selling_book| %>
                            <% if loved_book.book == selling_book.book %>
                             <%= cl_image_tag selling_book.book.photo.path, class: "book" %>
                            <% end %>
                          <% end %>
                        <% end %>
                    </div>
                  </div>
                </div>
              </div>

            </div>

          </div>
        <% end %>
      </div>
      <div class="col-xs-5" id="map-column">
        <div id="map"></div>
      </div>
    </div>
</div>


<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function () {
      var handler = Gmaps.build ('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(3);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  <% end %>
<% end %>

app/views/bookmates/search.html.erb
<% if @users_near_me.length == 0 %>
  <div class="container text-center">
      <h1>Oups...</h1>
      <p>Il n'y a personne autour de vous qui ont aimé vos livres</p>
      <p>Vous pouvez visiter les boutiques de tous les vendeurs sur BookShare en cliquant sur le bouton</p>
      <div id="btn-bookmates">
        <%= link_to "Voir les vendeurs", bookmates_path, class: "btn-bookshare-red"%>
      </div>
  </div>
<% else %>
  <div class="container-search">
  <!-- Bloc map et cards -->
    <div class="row">
        <!-- Bloc cards -->

        <div class="col-xs-7" id="card-column">
          <% @bookmates_selected.each do |bookmate|%>
            <!-- Carte utilisateur -->
            <div class="position-relative">

              <div class="card-grey-dashboard">

                <div class="order-bookmate text-center">
                    <% if bookmate.user.photo? %>
                      <%= cl_image_tag bookmate.user.photo.path,:width=>80, :height=>80, :gravity=>"auto", :crop=>"fill", class: "bookmate-avatar" %>
                    <% else %>
                      <%= image_tag 'avatar.png',:width=>80, :height=>80, :gravity=>"auto", :crop=>"fill" %>
                    <% end %>
                </div>

                <div class="user-details">
                  <%= link_to bookmate_path(bookmate) do %>

                    <h2 class="dark-grey weighted"><%= bookmate.user.first_name %></h2>
                    <p>" <%= bookmate.description %> "</p>
                  <% end %>

                  <!-- <h2 style="padding-left: 30vh"> -->
                  <div class="rating-search">
                    <p class="blue"> <i class="fa fa-commenting"></i> <%= bookmate.review_count%></p>
                    <% if bookmate.average_rating %>
                      <% bookmate.average_rating.times do %>
                        <i class="fa fa-star blue"></i>
                      <% end %>
                      <% (5 - bookmate.average_rating).times do %>
                        <i class="fa fa-star grey"></i>
                      <% end %>
                    <% end %>
                  </div>
                  <!-- </h2> -->
                </div>


                <div class="common-book-number" data-toggle="modal" data-target="#common-books-modal<%= bookmate.id %>">
                  <% if bookmate.respond_to?(:common_books) %>
                      <%= pluralize bookmate.common_books, "livre" %> en commun
                  <% else %>
                      Aucun livre en commun
                  <% end %>

                </div>

                <div class="modal fade books-modal" id="common-books-modal<%= bookmate.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <% if bookmate.respond_to?(:common_books) %>
                           <h3>Vos livres en commun avec <%= bookmate.user.first_name %></h3>
                      <% else %>
                          <h3>Vous n'avez aucun livre en commun avec <%= bookmate.user.first_name %> </h3>
                      <% end %>

                      <div class="common-books">

                          <% current_user.loved_books.each do |loved_book| %>
                            <% bookmate.selling_books.each do |selling_book| %>
                              <% if loved_book.book == selling_book.book %>
                               <%= cl_image_tag selling_book.book.photo.path, class: "book" %>
                              <% end %>
                            <% end %>
                          <% end %>
                      </div>
                    </div>
                  </div>
                </div>

              </div>

            </div>
          <% end %>
        </div>
        <div class="col-xs-5" id="map-column">
          <div id="map"></div>
        </div>
      </div>
  </div>
<% end %>


<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function () {
      var handler = Gmaps.build ('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(3);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  <% end %>
<% end %>

app/views/bookmates/show.html.erb
<div class="sidebar" id="side-bar">
  <div class="text-center bookmate-avatar">
    <%= cl_image_tag @bookmate.user.photo.path, alt: "profile picture", class: "avatar avatar-medium border-white text-center" %>
  </div>
  <h3>GENRES FAVORIS</h3>
  <!-- nav nav-list required by bootstrap to automatiquely active tab on scrolling -->
  <ul class="nav nav-list bookmate-tabs" role="tablist" >
    <% @bookmate.bookmate_book_categories.each do |bookmate_book_category| %>
    <!-- data-attr-scroll & class scrollto for scroll on click -->
      <li class ="bookmate-tab-link">
        <a href = "#category_<%= bookmate_book_category.id %>" class="scroll">
          <%= bookmate_book_category.name %>
        </a>
      </li>
    <% end %>
  </div>
  </ul>
</div>
  <!-- data-spy="scroll" required by bootstrap to automatiquely active tab on scrolling -->
  <div class = "col-xs-offset-2 col-xs-10" id="card-column-bookmate" data-spy="scroll" data-target="#side-bar">
  <div class="">
    <div class = "tab-content">
      <div class="inline-block">
        <h1><span class="red">A propos de <%= @bookmate.user.first_name %></span>

          <% if current_user.loved_bookstores.where(bookmate: @bookmate).exists? %>
            <%= link_to bookmate_loved_bookstore_path(@bookmate), method: :delete, class: "blue"  do %>
              <i class="fa fa-heart" ></i>
            <% end %>
          <% else %>
            <%= link_to bookmate_loved_bookstore_path(@bookmate), method: :post, class: "blue" do %>
              <i class="fa fa-heart-o" ></i>
            <% end %>
          <% end %>
        </h1>
      </div>

      <h2>Ses goûts littéraires :  </h2>
      <p><%= @bookmate.description %></p>

      <div class="book-categories">
      <% @bookmate.bookmate_book_categories.each do |bookmate_book_category| %>
        <div id ="category_<%= bookmate_book_category.id %>">
            <h2 class="red"><%= bookmate_book_category.name %></h2>
            <div class="bookmate-books">
              <div class="books">
                <% bookmate_book_category.selling_books.each do |selling_book| %>
                <div class="book">
                  <% if selling_book.sold %>
                    <p>Vendu à mettre en bannière sur la card</p>
                  <% end %>
                    <%= link_to bookmate_selling_book_path(@bookmate, selling_book) do %>
                       <%= cl_image_tag selling_book.book.photo.path %>
                    <% end %>
                </div>
              <% end %>
              </div>
            </div>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>



<% content_for :after_js do %>
  <%= javascript_tag do %>
    $(document).ready(function() {

      $(function(){

        $(".follow_option").on("click", function(e){
          <!-- // Change active tab -->
          $(".fa-bookmark-o").hide();
          $(".fa-bookmark").show();
        });
      });

    });
  <% end %>
<% end %>